engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php

ratings:
  paths:
    - "src/**/*.php"
